stages:
  - stage: SonarQube
    jobs:
      - job: SonarQube
        steps:
          - script: |
              echo sonarqube check


  - stage: UnitTest
    jobs:
      - job: UnitTest
        steps:
          - script: |
              echo unit test check


  - stage: DockerBuild
    jobs:
      - job: DockerBuild
        steps:
          - script: |
              echo "i m here"    
              docker build -t catalogue .

  - stage: DockerPush
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    jobs:
      - job: DockerPush
        steps:
          - script: |
              aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 224244588016.dkr.ecr.us-east-1.amazonaws.com
              docker tag ${COMPONENT}:latest 224244588016.dkr.ecr.us-east-1.amazonaws.com/${COMPONENT}:${BUILD_SOURCEBRANCHNAME}
              docker push 224244588016.dkr.ecr.us-east-1.amazonaws.com/${COMPONENT}:${BUILD_SOURCEBRANCHNAME}
